server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sa_beforeclass_springcloud
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.pointink.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
